ls:
  .dir: lowercase
  .py: lowercase
  .ipynb: lowercase
  .txt: lowercase
  .yml: lowercase
  .yaml: lowercase
  .json: lowercase

ignore:
  - .git
  - node_modules
  - venv
  - .venv
  - __pycache__
  - README.md
  - "**/README.md"
  - CONTRIBUTING.md
